javaScriptPoolSize: ${POOL_SIZE:-2}

rawrepoRecordServiceUrl: ${RAWREPO_RECORD_SERVICE_URL}

restClient:
  timeout: ${FETCH_RECORDS_TIMEOUT:-30}s
  connectionTimeout: 500ms
  timeToLive: 1 hour
  cookiesEnabled: false
  maxConnections: 1024
  maxConnectionsPerRoute: 1024
  keepAlive: 10s
  minThreads: 1
  maxThreads: 128
  gzipEnabled: true
  gzipEnabledForRequests: true


server:
# *** logback requestlog
  type: dbc
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081